In [5]:
import numpy as np

In [6]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [7]:
array_a=np.array([1,2,3,4])

In [8]:
array_b=np.array([0,.5,1,1.5,2])

In [9]:
array_b

array([0. , 0.5, 1. , 1.5, 2. ])

In [10]:
array_b

array([0. , 0.5, 1. , 1.5, 2. ])

In [11]:
array_a[0]

1

In [12]:
array_b[-1]

2.0

In [13]:
array_a[:2]

array([1, 2])

In [14]:
array_a.dtype

dtype('int32')

In [15]:
array_b.dtype

dtype('float64')

In [16]:
np.array([1,2,3,4],dtype=np.float_)

array([1., 2., 3., 4.])

In [17]:
np.array([1,2,3,4],dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [18]:
array_c=np.array(["ada","lovelace"])

In [19]:
array_c.dtype

dtype('<U8')

Diemensions and shapes

In [20]:
my_array = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [23]:
array_a.shape ###

(4,)

In [27]:
my_array.shape ## my_array in boyutudur.

(2, 3)

In [28]:
array_a.ndim

1

In [29]:
my_array.ndim #my_array in boyutunu döndürür.

2

In [30]:
my_array.size

6

In [31]:
my_array = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 6],
        [3, 2, 1]
    ]
])

In [32]:
my_array.ndim

3

In [33]:
my_array.shape

(2, 2, 3)

In [34]:
my_array.size

12

Indexing and Slicing

In [35]:
my_array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]    
])

In [36]:
my_array[1]

array([4, 5, 6])

In [38]:
my_array[1][0]

4

In [39]:
my_array[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
my_array[:2,:2]

array([[1, 2],
       [4, 5]])

In [41]:
my_array[1]=np.array([10,10,10])

In [42]:
my_array

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [43]:
my_array[2]=99

In [44]:
my_array

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [45]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [46]:
my_array=np.arange(0,10)

In [47]:
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
my_array.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [49]:
np.arange(1, 10.1,4)

array([1., 5., 9.])

In [50]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [51]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [52]:
np.ones((2,5,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [53]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
my_array=np.random.random((5,2))

In [55]:
my_array

array([[0.30344249, 0.2888652 ],
       [0.66056116, 0.84096496],
       [0.41152473, 0.96389751],
       [0.14339575, 0.8620858 ],
       [0.53149219, 0.03771677]])

In [56]:
np.random.randint(100, size=(5,5))

array([[97, 26, 74, 45, 26],
       [43, 64, 17,  6, 10],
       [69, 58, 95, 60, 91],
       [47, 17, 29, 17,  3],
       [ 3, 67, 75, 14, 99]])

In [57]:
np.linspace(5,10,5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

#any(),all(),full(),concatenate()

In [58]:
array1=np.arange(0,10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
array1 = array1.reshape(2,5)

In [60]:
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [61]:
np.concatenate([array1,array1])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [62]:
np.concatenate([array1,array1], axis=1)

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

Statistics

In [64]:
array1=np.arange(0,10).reshape(2,5)


In [65]:
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [66]:
array1.sum()

45

In [67]:
array1.mean()

4.5

In [68]:
array1.std()

2.8722813232690143

In [69]:
array1.var()

8.25

In [70]:
array1.sum(axis=1)

array([10, 35])

In [71]:
array1.sum(axis=0)

array([ 5,  7,  9, 11, 13])

In [73]:
array1 + 10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [74]:
array1 +=10
array1

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [75]:
array2=np.arange(0,10).reshape(5,2)

In [76]:
array2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [77]:
array2+10

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

Boolean Arrays

In [78]:
a= np.arange(4)

In [79]:
a

array([0, 1, 2, 3])

In [80]:
a[0],a[-1]

(0, 3)

In [81]:
a[[0, -1]]

array([0, 3])

In [82]:
a[[True, False, False, True]]

array([0, 3])

In [83]:
a>=2

array([False, False,  True,  True])

In [84]:
a[a>=2]

array([2, 3])

In [85]:
a.mean()

1.5

In [86]:
a[a>a.mean()]

array([2, 3])

In [87]:
a[(a==0)|(a==1)]

array([0, 1])

In [88]:
a[(a<=2)&(a%2==0)]

array([0, 2])

Örnek Soru:
100'e kadar rastgele tamsayılardan oluşan,  3,3 bir matris oluşturun.
30'dan büyük olanları boolean yöntemi ile filtreleyin.

In [89]:
rand_array = np.random.randint(100,size=(3,3))

In [90]:
rand_array

array([[50, 87, 63],
       [94, 79, 92],
       [95, 52, 37]])

In [91]:
boolean_array= rand_array>30

In [92]:
boolean_array

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [93]:
rand_array[boolean_array]

array([50, 87, 63, 94, 79, 92, 95, 52, 37])

In [94]:
my_array = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
array_1 = my_array.reshape(5,2)
array_2 = my_array.reshape(2,5)

In [98]:
array_1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [99]:
array_2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [100]:
np.dot(array_1,array_2)

array([[  5,   6,   7,   8,   9],
       [ 15,  20,  25,  30,  35],
       [ 25,  34,  43,  52,  61],
       [ 35,  48,  61,  74,  87],
       [ 45,  62,  79,  96, 113]])

In [101]:
array_2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [102]:
import sys

In [103]:
sys.getsizeof(10)

28

In [104]:
sys.getsizeof(1000*100)

28

In [105]:
np.dtype(int).itemsize

4

In [106]:
np.dtype(np.int8).itemsize

1

In [107]:
np.dtype(float).itemsize

8

In [108]:
sys.getsizeof([1,2,3])

88

In [111]:
np.array([1,2,3]).nbytes

12

In [112]:
my_list = list(range(100000))

In [113]:
my_array = np.arange(100000)

In [114]:
%time np.sum(my_array**2)

CPU times: total: 0 ns
Wall time: 1.99 ms


216474736

In [115]:
%time sum([number ** 2 for number in my_list])

CPU times: total: 15.6 ms
Wall time: 46.9 ms


333328333350000